### ISSUE TITLE
Release-data is no more updated since 2023-07-13

### ISSUE THREAD

**Issue by marcwrobel** [endoflife-date/release-data#121]
The auto-commit action systematically fail with the following error:

```
INPUT_PUSH_OPTIONS: 
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Required status check "Update data" is expected.        
To https://github.com/endoflife-date/release-data
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/endoflife-date/release-data'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by captn3m0** [comment]
Ouch, removed the branch protection rule, and re-triggered the last failed build. Sorry about this.

Will have to re-think what's the best way to do this.

**Comment by marcwrobel** [comment]
Yep, and it would be great being able to manually trigger endoflife.date's `auto-merge-release-updates.yml` easily too.
